BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        id: Clear_all
        text: 'Clear'
        on_press: app.clean_all()

    TextInput:
        id: input_name
        text: ''
    Button:
        id: Button_3
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: "Enter your name"
        color: (1, 1, 0, 1)
